### ISSUE TITLE
Compile error after dhcp lib update

### ISSUE THREAD

**Issue by mahadeva604** [facebookincubator/dhcplb#23]
src/github.com/facebookincubator/dhcplb/lib/handler.go:269:20: undefined: dhcpv6.DHCPv6Relay
src/github.com/facebookincubator/dhcplb/lib/handler.go:276:15: undefined: dhcpv6.DHCPv6Message
src/github.com/facebookincubator/dhcplb/lib/handler.go:322:23: undefined: dhcpv6.DHCPv6Relay

**Comment by pallotron** [comment]
We will take a look today. Cc @pmazzini

**Comment by pmazzini** [comment]
This is due to the changes that were introduced in https://github.com/insomniacslk/dhcp/pull/253. I will fix it ASAP.
@mahadeva604 Thanks for reporting it.

**Comment by pmazzini** [comment]
Updated.
