### ISSUE TITLE
"undefined: dhcpv6.OptClientId" error during "go get github.com/facebookincubator/dhcplb"

### ISSUE THREAD

**Issue by abckey** [facebookincubator/dhcplb#30]
In my vagrant setup, I started to face this probelm recently.

root@dhcplb:~# go get github.com/facebookincubator/dhcplb
/opt/go/src/github.com/facebookincubator/dhcplb/lib/handler.go:276:24: undefined: dhcpv6.OptClientId

root@dhcplb:~# go version
go version go1.13 linux/amd64

**Comment by insomniacslk** [comment]
This was broken by https://github.com/insomniacslk/dhcp/pull/343 , I'll put up a fix

**Comment by insomniacslk** [comment]
first of two fixes: https://github.com/insomniacslk/dhcp/pull/364

**Comment by insomniacslk** [comment]
also pending https://github.com/insomniacslk/dhcp/pull/349
